metadata:
  rowCount: 5
  delimiter: ','
corruption:
  enabled: false
  chance: 0.01
  minimum: 1
  maximum: 4
  method: DATA_TYPE
columns:
  - label: First Name
    source: FIRST_NAME
    order: 1
  - label: Last Name
    source: LAST_NAME
    order: 2
  - label: Birthday
    source: TIMESTAMP
    timestampConstraint:
      format: 2006-01-02
      after: 1910-01-01
      before: 2023-05-29
  - label: Group
    source: INTEGER
    order: 0
    numericConstraint:
      min: 1
      max: 9
  - label: Some Text
    source: STRING
    stringConstraint:
      regex: '^[a-zA-Z0-9_]{6}$'
  - label: Country of Origin
    source: COUNTRY
    order: 3
